// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.6.1
// source: pricing_service/pricing_service.proto

package pricing

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pricing_PricingType int32

const (
	Pricing_PER_PERSON    Pricing_PricingType = 0
	Pricing_PER_HOUSEHOLD Pricing_PricingType = 1
)

// Enum value maps for Pricing_PricingType.
var (
	Pricing_PricingType_name = map[int32]string{
		0: "PER_PERSON",
		1: "PER_HOUSEHOLD",
	}
	Pricing_PricingType_value = map[string]int32{
		"PER_PERSON":    0,
		"PER_HOUSEHOLD": 1,
	}
)

func (x Pricing_PricingType) Enum() *Pricing_PricingType {
	p := new(Pricing_PricingType)
	*p = x
	return p
}

func (x Pricing_PricingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pricing_PricingType) Descriptor() protoreflect.EnumDescriptor {
	return file_pricing_service_pricing_service_proto_enumTypes[0].Descriptor()
}

func (Pricing_PricingType) Type() protoreflect.EnumType {
	return &file_pricing_service_pricing_service_proto_enumTypes[0]
}

func (x Pricing_PricingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pricing_PricingType.Descriptor instead.
func (Pricing_PricingType) EnumDescriptor() ([]byte, []int) {
	return file_pricing_service_pricing_service_proto_rawDescGZIP(), []int{4, 0}
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pricing_service_pricing_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_service_pricing_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pricing_service_pricing_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pricing *Pricing `protobuf:"bytes,1,opt,name=pricing,proto3" json:"pricing,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pricing_service_pricing_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_service_pricing_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_pricing_service_pricing_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetPricing() *Pricing {
	if x != nil {
		return x.Pricing
	}
	return nil
}

type GetByAccommodationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccommodationId string `protobuf:"bytes,1,opt,name=accommodation_id,json=accommodationId,proto3" json:"accommodation_id,omitempty"`
}

func (x *GetByAccommodationRequest) Reset() {
	*x = GetByAccommodationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pricing_service_pricing_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByAccommodationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByAccommodationRequest) ProtoMessage() {}

func (x *GetByAccommodationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_service_pricing_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByAccommodationRequest.ProtoReflect.Descriptor instead.
func (*GetByAccommodationRequest) Descriptor() ([]byte, []int) {
	return file_pricing_service_pricing_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetByAccommodationRequest) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

type GetByAccommodationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pricing *Pricing `protobuf:"bytes,1,opt,name=pricing,proto3" json:"pricing,omitempty"`
}

func (x *GetByAccommodationResponse) Reset() {
	*x = GetByAccommodationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pricing_service_pricing_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByAccommodationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByAccommodationResponse) ProtoMessage() {}

func (x *GetByAccommodationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_service_pricing_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByAccommodationResponse.ProtoReflect.Descriptor instead.
func (*GetByAccommodationResponse) Descriptor() ([]byte, []int) {
	return file_pricing_service_pricing_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetByAccommodationResponse) GetPricing() *Pricing {
	if x != nil {
		return x.Pricing
	}
	return nil
}

type Pricing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccommodationId string              `protobuf:"bytes,2,opt,name=accommodation_id,json=accommodationId,proto3" json:"accommodation_id,omitempty"`
	Price           float32             `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	Season          *Season             `protobuf:"bytes,4,opt,name=season,proto3" json:"season,omitempty"`
	Week            *Week               `protobuf:"bytes,5,opt,name=week,proto3" json:"week,omitempty"`
	Holiday         float32             `protobuf:"fixed32,6,opt,name=holiday,proto3" json:"holiday,omitempty"`
	PricingType     Pricing_PricingType `protobuf:"varint,7,opt,name=pricingType,proto3,enum=pricing.Pricing_PricingType" json:"pricingType,omitempty"`
}

func (x *Pricing) Reset() {
	*x = Pricing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pricing_service_pricing_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pricing) ProtoMessage() {}

func (x *Pricing) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_service_pricing_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pricing.ProtoReflect.Descriptor instead.
func (*Pricing) Descriptor() ([]byte, []int) {
	return file_pricing_service_pricing_service_proto_rawDescGZIP(), []int{4}
}

func (x *Pricing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pricing) GetAccommodationId() string {
	if x != nil {
		return x.AccommodationId
	}
	return ""
}

func (x *Pricing) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Pricing) GetSeason() *Season {
	if x != nil {
		return x.Season
	}
	return nil
}

func (x *Pricing) GetWeek() *Week {
	if x != nil {
		return x.Week
	}
	return nil
}

func (x *Pricing) GetHoliday() float32 {
	if x != nil {
		return x.Holiday
	}
	return 0
}

func (x *Pricing) GetPricingType() Pricing_PricingType {
	if x != nil {
		return x.PricingType
	}
	return Pricing_PER_PERSON
}

type Season struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpringMultiplier float32 `protobuf:"fixed32,1,opt,name=springMultiplier,proto3" json:"springMultiplier,omitempty"`
	SummerMultiplier float32 `protobuf:"fixed32,2,opt,name=summerMultiplier,proto3" json:"summerMultiplier,omitempty"`
	FallMultiplier   float32 `protobuf:"fixed32,3,opt,name=fallMultiplier,proto3" json:"fallMultiplier,omitempty"`
	WinterMultiplier float32 `protobuf:"fixed32,4,opt,name=winterMultiplier,proto3" json:"winterMultiplier,omitempty"`
}

func (x *Season) Reset() {
	*x = Season{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pricing_service_pricing_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Season) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Season) ProtoMessage() {}

func (x *Season) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_service_pricing_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Season.ProtoReflect.Descriptor instead.
func (*Season) Descriptor() ([]byte, []int) {
	return file_pricing_service_pricing_service_proto_rawDescGZIP(), []int{5}
}

func (x *Season) GetSpringMultiplier() float32 {
	if x != nil {
		return x.SpringMultiplier
	}
	return 0
}

func (x *Season) GetSummerMultiplier() float32 {
	if x != nil {
		return x.SummerMultiplier
	}
	return 0
}

func (x *Season) GetFallMultiplier() float32 {
	if x != nil {
		return x.FallMultiplier
	}
	return 0
}

func (x *Season) GetWinterMultiplier() float32 {
	if x != nil {
		return x.WinterMultiplier
	}
	return 0
}

type Week struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkdayMultiplier float32 `protobuf:"fixed32,1,opt,name=workdayMultiplier,proto3" json:"workdayMultiplier,omitempty"`
	WeekendMultiplier float32 `protobuf:"fixed32,2,opt,name=weekendMultiplier,proto3" json:"weekendMultiplier,omitempty"`
}

func (x *Week) Reset() {
	*x = Week{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pricing_service_pricing_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Week) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Week) ProtoMessage() {}

func (x *Week) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_service_pricing_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Week.ProtoReflect.Descriptor instead.
func (*Week) Descriptor() ([]byte, []int) {
	return file_pricing_service_pricing_service_proto_rawDescGZIP(), []int{6}
}

func (x *Week) GetWorkdayMultiplier() float32 {
	if x != nil {
		return x.WorkdayMultiplier
	}
	return 0
}

func (x *Week) GetWeekendMultiplier() float32 {
	if x != nil {
		return x.WeekendMultiplier
	}
	return 0
}

var File_pricing_service_pricing_service_proto protoreflect.FileDescriptor

var file_pricing_service_pricing_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x70,
	0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70,
	0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x52, 0x07,
	0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x22, 0x46, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x48, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x07, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67,
	0x52, 0x07, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x22, 0xb2, 0x02, 0x0a, 0x07, 0x50, 0x72,
	0x69, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67,
	0x2e, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x21, 0x0a, 0x04, 0x77, 0x65, 0x65, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x57, 0x65, 0x65, 0x6b, 0x52, 0x04, 0x77, 0x65,
	0x65, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x07, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x12, 0x3e, 0x0a, 0x0b,
	0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x72, 0x69, 0x63,
	0x69, 0x6e, 0x67, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0b, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x22, 0x30, 0x0a, 0x0b,
	0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x50,
	0x45, 0x52, 0x5f, 0x50, 0x45, 0x52, 0x53, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x50,
	0x45, 0x52, 0x5f, 0x48, 0x4f, 0x55, 0x53, 0x45, 0x48, 0x4f, 0x4c, 0x44, 0x10, 0x01, 0x22, 0xb4,
	0x01, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x70, 0x72,
	0x69, 0x6e, 0x67, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x10, 0x73, 0x70, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x69, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x10, 0x73, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65,
	0x72, 0x12, 0x26, 0x0a, 0x0e, 0x66, 0x61, 0x6c, 0x6c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c,
	0x69, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0e, 0x66, 0x61, 0x6c, 0x6c, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x77, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x10, 0x77, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x69, 0x65, 0x72, 0x22, 0x62, 0x0a, 0x04, 0x57, 0x65, 0x65, 0x6b, 0x12, 0x2c, 0x0a,
	0x11, 0x77, 0x6f, 0x72, 0x6b, 0x64, 0x61, 0x79, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x11, 0x77, 0x6f, 0x72, 0x6b, 0x64, 0x61,
	0x79, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x11, 0x77,
	0x65, 0x65, 0x6b, 0x65, 0x6e, 0x64, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x11, 0x77, 0x65, 0x65, 0x6b, 0x65, 0x6e, 0x64, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x32, 0xde, 0x01, 0x0a, 0x0e, 0x50, 0x72,
	0x69, 0x63, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x03,
	0x47, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x69,
	0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67,
	0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x82, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x79, 0x41,
	0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x2e, 0x70,
	0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x41, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x12, 0x1b, 0x2f,
	0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x2f, 0x7b, 0x61, 0x63, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x7d, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x2d, 0x6d, 0x61, 0x74, 0x6b, 0x65,
	0x2f, 0x61, 0x62, 0x70, 0x2f, 0x61, 0x62, 0x70, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pricing_service_pricing_service_proto_rawDescOnce sync.Once
	file_pricing_service_pricing_service_proto_rawDescData = file_pricing_service_pricing_service_proto_rawDesc
)

func file_pricing_service_pricing_service_proto_rawDescGZIP() []byte {
	file_pricing_service_pricing_service_proto_rawDescOnce.Do(func() {
		file_pricing_service_pricing_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pricing_service_pricing_service_proto_rawDescData)
	})
	return file_pricing_service_pricing_service_proto_rawDescData
}

var file_pricing_service_pricing_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pricing_service_pricing_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pricing_service_pricing_service_proto_goTypes = []interface{}{
	(Pricing_PricingType)(0),           // 0: pricing.Pricing.PricingType
	(*GetRequest)(nil),                 // 1: pricing.GetRequest
	(*GetResponse)(nil),                // 2: pricing.GetResponse
	(*GetByAccommodationRequest)(nil),  // 3: pricing.GetByAccommodationRequest
	(*GetByAccommodationResponse)(nil), // 4: pricing.GetByAccommodationResponse
	(*Pricing)(nil),                    // 5: pricing.Pricing
	(*Season)(nil),                     // 6: pricing.Season
	(*Week)(nil),                       // 7: pricing.Week
}
var file_pricing_service_pricing_service_proto_depIdxs = []int32{
	5, // 0: pricing.GetResponse.pricing:type_name -> pricing.Pricing
	5, // 1: pricing.GetByAccommodationResponse.pricing:type_name -> pricing.Pricing
	6, // 2: pricing.Pricing.season:type_name -> pricing.Season
	7, // 3: pricing.Pricing.week:type_name -> pricing.Week
	0, // 4: pricing.Pricing.pricingType:type_name -> pricing.Pricing.PricingType
	1, // 5: pricing.PricingService.Get:input_type -> pricing.GetRequest
	3, // 6: pricing.PricingService.GetByAccommodation:input_type -> pricing.GetByAccommodationRequest
	2, // 7: pricing.PricingService.Get:output_type -> pricing.GetResponse
	4, // 8: pricing.PricingService.GetByAccommodation:output_type -> pricing.GetByAccommodationResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pricing_service_pricing_service_proto_init() }
func file_pricing_service_pricing_service_proto_init() {
	if File_pricing_service_pricing_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pricing_service_pricing_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pricing_service_pricing_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pricing_service_pricing_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByAccommodationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pricing_service_pricing_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByAccommodationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pricing_service_pricing_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pricing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pricing_service_pricing_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Season); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pricing_service_pricing_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Week); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pricing_service_pricing_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pricing_service_pricing_service_proto_goTypes,
		DependencyIndexes: file_pricing_service_pricing_service_proto_depIdxs,
		EnumInfos:         file_pricing_service_pricing_service_proto_enumTypes,
		MessageInfos:      file_pricing_service_pricing_service_proto_msgTypes,
	}.Build()
	File_pricing_service_pricing_service_proto = out.File
	file_pricing_service_pricing_service_proto_rawDesc = nil
	file_pricing_service_pricing_service_proto_goTypes = nil
	file_pricing_service_pricing_service_proto_depIdxs = nil
}
